#!/usr/bin/env bash

# If the number of images in a directory is equal or larger than this value,
# this program converts them into a PDF.
: ${IMAGE_SET_SIZE_THRESOLD:=3}

# The quality of images. This value will be passed to ImageMagick. This is
# useful to reduce the size of output file to avoid the upload limitations on
# Google Play Books.
: ${IMAGE_QUALITY:=50%}

# The template for output PDF filenames. You can use these placeholders:
# {series_name} -> series name
# {series_no}   -> series no
: ${PDF_FILENAME_TEMPLATE:='{series_name} {series_no}.pdf'}

declare unar_available=0
declare ditto_available=0
declare unzip_available=0
declare unrar_available=0

if hash unar 2>/dev/null; then
  unar_available=1
fi
if [[ "$OSTYPE" == darwin* ]] && hash ditto 2>/dev/null; then
  ditto_available=1
fi
if hash unzip 2>/dev/null; then
  unzip_available=1
fi
if hash unrar 2>/dev/null; then
  unrar_available=1
fi

shopt -s extglob

recursively_process() {
  local target="$1"

  if is_archive "$target"; then
    recursively_process_archive "$target"
  elif [[ -d "$target" ]]; then
    recursively_process_directory "$target"
  fi
}

is_archive() {
  [[ -f "$target" && "$target" =~ \.(zip|rar)$ ]]
}

recursively_process_archive() {
  local archive="$1"

  if ! is_archive "$archive"; then
    echo "Unknown or unsupported archive type: $archive" >&2
    exit 1
  fi

  local temp_directory
  temp_directory="$(mktemp -d)"
  echo "Uncompressing \"${archive##*/}\" to \"${temp_directory}\""

  # The Unarchiver can automatically detect encoding for filenames, and support
  # various archive types.
  # See https://theunarchiver.com/command-line
  if [[ "${unar_available}" == 1 ]]; then
    unar -o "$temp_directory" -q "$archive"
  elif [[ "$archive" == *.zip ]]; then
    if [[ "${ditto_available}" ]]; then
      ditto -xk "$archive" "$temp_directory" >/dev/null
    elif [[ "${unzip_available}" ]]; then
      unzip "$archive" -d "$temp_directory" >/dev/null
    else
      echo 'Error: You need ditto or unzip in executable paths to unarchive' \
        'ZIP archive.' >&2
      exit 127
    fi
  elif [[ "$archive" == *.rar ]]; then
    if [[ "${unrar_available}" ]]; then
      unrar x "$archive" "$temp_directory" >/dev/null
    else
      echo 'Error: You need unrar in executable paths to unarchive RAR' \
        'archive.' >&2
      exit 127
    fi
  fi

  recursively_process_directory "$temp_directory"

  rm -rf "$temp_directory"
}

extract_series_name() {
  local file_basename="$1"

  file_basename="${file_basename#\(*\)}"
  file_basename="${file_basename#\[*\]}"
  file_basename="${file_basename##*([ 　])}"
  file_basename="${file_basename%[ 　]*}"
  file_basename="${file_basename%%*([ 　])}"

  echo "$file_basename"
}

extract_series_no() {
  local file_basename="$1"

  file_basename="${file_basename##*[ 　]}"
  file_basename="${file_basename//[!0-9]/}"

  echo "$file_basename"
}

pdf_filename() {
  local directory_basename="$1"

  if [[ -n "$PDF_FILENAME_TEMPLATE" ]]; then
    local series_name="$(extract_series_name "$directory_basename")"
    local series_no="$(extract_series_no "$directory_basename")"

    if [[ -n "$series_name" && -n "$series_no" ]]; then
      local filename="$PDF_FILENAME_TEMPLATE"
      filename="${filename/\{series_name\}/$series_name}"
      filename="${filename/\{series_no\}/$series_no}"
      echo "$filename"
      return 0
    fi
  fi

  echo "${directory_basename}.pdf"
}

recursively_process_directory() {
  local directory="$1"
  local -a images
  local image
  local a_directory
  local an_archive

  while IFS='' read -r image; do
    images+=("$image")
  done < <(find "$directory" -mindepth 1 -maxdepth 1 -type f -name '*.jpg' |
    sort)

  if [[ "$IMAGE_SET_SIZE_THRESOLD" -le "${#images}" ]]; then
    local pdf_filename="$(pdf_filename "${directory##*/}")"
    echo "Converting ${#images[@]} images into \"${pdf_filename}\"."
    convert "${images[@]}" -quality "$IMAGE_QUALITY" "$pdf_filename"

    local pdf_filesize
    pdf_filesize="$(wc -c "$pdf_filename" | cut -d' ' -f2)"
    pdf_filesize="$((pdf_filesize / 1024 / 1024))"
    if [[ 100 -le "$pdf_filesize" ]]; then
      echo "Warning: \"$pdf_filename\" is over 100MB, you can't upload it on" \
        'Google Play Books.' >&2
    fi
  fi

  while IFS='' read -r a_directory; do
    recursively_process_directory "$a_directory"
  done < <(find "$directory" -mindepth 1 -maxdepth 1 -type d)

  while IFS='' read -r an_archive; do
    recursively_process_archive "$an_archive"
  done < <(find "$directory" \
    -mindepth 1 \
    -maxdepth 1 \
    -type f \
    \( -name '*.zip' -o -name '*.rar' \))
}

main() {
  local -a targets=("$@")
  if [[ "${#targets[@]}" == 0 ]]; then
    targets+=("$PWD")
  fi

  recursively_process "${targets[@]}"
}

main "$@"
